### ISSUE TITLE
Nnot feeling well

### ISSUE THREAD

**Issue by Rienb** [HofmannZ/global-ai-hackathon-coin-truth#3]
Hey guys,

I'm really not feeling well, didn't sleep much due to fever. I'll be at the hackaton for the pitch and maybe earlier. I'll take care of myself at home and hopefully energetic and sharp in the afternoon.

**Comment by HofmannZ** [comment]
Hey man,

I'm sorry to hear that, hope you get well soon 🤒

**Comment by Lalo88** [comment]
Ok strength till later

**Comment by Rienb** [comment]
Still feeling weak but would like to help remotely. What tasks need to be done before the deadline?

**Comment by HofmannZ** [comment]
I think the white paper still needs to be done

**Comment by Rienb** [comment]
Nothing else? Everything is functioning and we have significant findings?

**Comment by Rienb** [comment]
i'll be at the VU at 13:00

**Comment by Lalo88** [comment]
Can you register yourself  on ai.platform.hackathon.com so I can add you on the team tnx
